### ISSUE TITLE
AMREX  is borken in xsdk@5.0

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#110]
Spack has the following for AMREX for older versions [newer versions appear to user tarballs]

```
    version('19.10', commit='52844b32b7da11e9733b9a7f4a782e51de7f5e1e')  # tag:19.10                                                                                            
    version('19.08', commit='bdd1146139e8727a513d451075f900c172eb81fd')  # tag:19.08                                                                                            
    version('18.10.1', commit='260b53169badaa760b91dfc60ea6b2ea3d9ccf06')  # tag:18.10.1                                                                                        
    version('18.10', commit='d37a266c38092e1174096e245326e9eead1f4e03')  # tag:18.10                                                                                            
    version('18.09.1', commit='88120db4736c325a2d3d2c291adacaffd3bf224b')  # tag:18.09.1                                                                                        
````
However spack gives errors.
```
[balay@pj01 spack]$ spack fetch amrex@19.08
==> Cloning git repository: https://github.com/AMReX-Codes/amrex.git at commit bdd1146139e8727a513d451075f900c172eb81fd
fatal: reference is not a tree: bdd1146139e8727a513d451075f900c172eb81fd
==> Fetching from [git] https://github.com/AMReX-Codes/amrex.git at commit bdd1146139e8727a513d451075f900c172eb81fd failed.
==> Error: All fetchers failed for spack-stage-amrex-19.08-45qrfp43j52gop4d6zvaf5ikjt4ywz5i
```
I see this commit at github

https://github.com/AMReX-Codes/amrex/commit/bdd1146139e8727a513d451075f900c172eb81fd

But I don't see a branch associated with it

```
balay@sb /home/balay/git-repo/github/amrex (development=)
$ git branch -r --contains bdd1146139e8727a513d451075f900c172eb81fd
error: no such commit bdd1146139e8727a513d451075f900c172eb81fd
```
Did all the prior release commits get rebased?

I guess we'll have to fix amrex in spack and use tarballs for all the old releases?

cc: @mic84

**Comment by mic84** [comment]
Hi Satish,
amrex history has been, in fact, re-written. Let me take care of this.

**Comment by balay** [comment]
@mic84  I have the following change. If ok - I can make a PR to spack

https://github.com/spack/spack/commit/bc49010a44b414b94f5c8d15c1fb49e3633c60ab

**Comment by mic84** [comment]
@balay I can't install any version of amrex, including 20.03 and 20.04. 

```
 ==> 18719: Installing amrex
==> Fetching https://github.com/AMReX-Codes/amrex/archive/20.03.tar.gz
########################################################################################################################################################################## 100.0%           -=O=-             #          #           #            #                                                                                                              
==> Error: ChecksumError: sha256 checksum failed for /tmp/mic/spack-stage-amrex-20.03-i7cunza5hkoahrlrgcznwrifcimglcmc/20.03.tar.gz
    Expected a535dcc016f0d38b55d0ab8e9067c1c53e3686961f6a1fb471cb18a0ebc909e6 but got 9728f20c0d7297c935fe5cbc63c1ee60f983b833a735c797340ee2765d626165

/home/mic/Documents/GitCodes/spack/lib/spack/spack/package.py:1146, in do_fetch:
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145
  >>   1146        if checksum and self.version in self.versions:
       1147            self.stage.check()
       1148
       1149        self.stage.cache_local()


==> Error: Failed to install amrex due to ChildError: ChecksumError: sha256 checksum failed for /tmp/mic/spack-stage-amrex-20.03-i7cunza5hkoahrlrgcznwrifcimglcmc/20.03.tar.gz
    Expected a535dcc016f0d38b55d0ab8e9067c1c53e3686961f6a1fb471cb18a0ebc909e6 but got 9728f20c0d7297c935fe5cbc63c1ee60f983b833a735c797340ee2765d626165
/home/mic/Documents/GitCodes/spack/lib/spack/spack/package.py:1146, in do_fetch:
       1143        self.stage.fetch(mirror_only)
       1144        self._fetch_time = time.time() - start_time
       1145
  >>   1146        if checksum and self.version in self.versions:
       1147            self.stage.check()
       1148
       1149        self.stage.cache_local()

Traceback (most recent call last):
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/build_environment.py", line 802, in child_process
    return_value = function()
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/installer.py", line 1056, in build_process
    pkg.do_patch()
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/package.py", line 1182, in do_patch
    self.do_stage()
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/package.py", line 1167, in do_stage
    self.do_fetch(mirror_only)
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/package.py", line 1147, in do_fetch
    self.stage.check()
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/stage.py", line 490, in check
    self.fetcher.check()
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/mic/Documents/GitCodes/spack/lib/spack/spack/fetch_strategy.py", line 504, in check
    "Expected %s but got %s" % (self.digest, checker.sum))
spack.fetch_strategy.ChecksumError: sha256 checksum failed for /tmp/mic/spack-stage-amrex-20.03-i7cunza5hkoahrlrgcznwrifcimglcmc/20.03.tar.gz
    Expected a535dcc016f0d38b55d0ab8e9067c1c53e3686961f6a1fb471cb18a0ebc909e6 but got 9728f20c0d7297c935fe5cbc63c1ee60f983b833a735c797340ee2765d626165
```

**Comment by balay** [comment]
Ah - I primarily tested amrex@19.08 via xsdk - and updated the other releases using commits.

I see the shasums have also changed for the tarballs - since the history for the repo is rewritten - and the traballs are just redirects to the tags and corresponding commits.

Will update these shasums aswell.

**Comment by balay** [comment]
https://github.com/spack/spack/tree/balay/update-amrex-sha256 is now updated

**Comment by tgamblin** [comment]
> I see the shasums have also changed for the tarballs - since the history for the repo is rewritten - and the traballs are just redirects to the tags and corresponding commits.


Note that if you want GitHub to maintain stable sha256sums for releases in situations like this, you can specifically attach an asset to each release.  See, e.g., here: 

* https://github.com/spack/spack/releases/tag/v0.14.2

The `spack-0.14.2.tar.gz` file that's attached to the release isn't auto-generated like the `Source code (tar.gz)` and `Source code (zip)` links.  We do this for every Spack release, and it's also kind of nice because you can actually get download counts via the API for files uploaded this way:

* https://api.github.com/repos/spack/spack/releases

The other links aren't tracked.

Anyway, it's good practice to do this because the checksums for the auto-generated tarballs aren't guaranteed to be stable even if you *don't* rewrite history.  See this:

* https://github.com/easybuilders/easybuild-easyconfigs/issues/5151

At one point they changed the compression algorithm used to generate the artifacts, and *every* `sha256` from the auto-generated URLs changed.  If you specifically upload an asset, though, it won't have this problem.

**Comment by tgamblin** [comment]
oops -- accidentally hit close instead of comment -- reopened.  😊

**Comment by mic84** [comment]
@balay your changes worked for me!

**Comment by balay** [comment]
Thanks! PR at: https://github.com/spack/spack/pull/16379
