### ISSUE TITLE
phist build failure with Python 3.11.0rc2

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#193]
```
  File "/home/balay/spack/spack-stage/spack-stage-phist-1.10.0-jkf3gwhrcomz3yew25suhfoz73amb4sj/spack-build-jkf3gwh/cxx_bindings/make_cxx_bindings.py", line 106, in <module>
    whole_file = open(mod_dir + "/" + c_file_name, 'rU').read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/9824859/spack-build-out.txt)

Might be same issue as: https://gitlab.com/petsc/petsc/-/merge_requests/5732/diffs?commit_id=0de5a3fe88a2a4e564488567dfae2e2466a112a4

**Comment by balay** [comment]
BTW: the release spreadsheet says `phist@1.10.0` - but I see `1.11.0`is also available in spack - so which one should we test with?

**Comment by balay** [comment]
For now - testing with: https://gitlab.com/xsdk-project/spack-xsdk/-/commit/9cbf3414d4e89f7b332f55705d1092dff93f141e

**Comment by balay** [comment]
```
3 errors found in build log:
     149    cd /home/balay/spack.x/spack-stage/spack-stage-phist-1.11.0-o3ncuefwlofg37ojr7cw3ii6yp3eub5b/spack-build-o3ncuef/cxx_bindings && /usr/bin/python3 /home/balay/spack.x/spack-stage/spack-stage-phist-1.
            11.0-o3ncuefwlofg37ojr7cw3ii6yp3eub5b/spack-build-o3ncuef/cxx_bindings/make_cxx_bindings.py
     150    Traceback (most recent call last):
     151      File "/home/balay/spack.x/spack-stage/spack-stage-phist-1.11.0-o3ncuefwlofg37ojr7cw3ii6yp3eub5b/spack-build-o3ncuef/cxx_bindings/make_cxx_bindings.py", line 106, in <module>
     152        whole_file = open(mod_dir + "/" + c_file_name, 'rU').read()
     153                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     154    ValueError: invalid mode: 'rU'
  >> 155    make[2]: *** [cxx_bindings/CMakeFiles/cxx_headers.dir/build.make:176: cxx_bindings/phist_kernels.hpp] Error 1
     156    make[2]: Leaving directory '/home/balay/spack.x/spack-stage/spack-stage-phist-1.11.0-o3ncuefwlofg37ojr7cw3ii6yp3eub5b/spack-build-o3ncuef'
  >> 157    make[1]: *** [CMakeFiles/Makefile2:1952: cxx_bindings/CMakeFiles/cxx_headers.dir/all] Error 2
     158    make[1]: *** Waiting for unfinished jobs....

```
```
[balay@pj01 spack.x]$ ./bin/spack find -p python
-- linux-fedora37-skylake / oneapi@2022.2.0 ---------------------
python@3.9.7  /opt/intel/oneapi/intelpython/python3.9
```
Here its not using python from depenedencies...

**Comment by jthies** [comment]
Hi @balay, thanks for the pointer to the petsc issue, if that's all it should be fixed in phist@develop now. For the xSDK release I could make a new tag (phist@1.11.2 or so) after you confirm that this fixes the build issue with python@3.11:

**Comment by balay** [comment]
Thanks! Added phist-dev branch as phist@1.11.2 - so this can tested. The python-3.11 build does go through with it.

**Comment by balos1** [comment]
Closing since this seems to have been fixed with the patch.
